
trigger:
- azure-pipelines

pool:
  name: Default

steps:           
- task: DownloadPipelineArtifact@2
  continueOnError: true
  inputs:
    buildType: 'specific'
    project: 'e299d603-e81a-46ba-92bd-f4ed1a9bccc6'
    definition: '1'
    artifactName: 'idir'
    targetPath: '.'

- task: synopsys-coverity@1
  inputs:
    coverityService: 'Coverity'
    projectName: 'azure-sample'
    streamName: 'azure-sample'
    coverityBuildDirectory: '$(Build.Repository.LocalPath)'
    buildCommand: 'mvn clean install'
    allowUntrusted: true
  displayName: 'Coverity Scan'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'idir'
    artifact: 'idir'
    publishLocation: 'pipeline'

